### ISSUE TITLE
Contact Trace fields bug and questions

### ISSUE THREAD

**Issue by jpbottinelli** [quarentime/quarentime-back-end#44]
After creating an user and checking the Contact Trace response, I found some things off:

1. Initials are broken -> It should be TNU1, all in capital letters.
1. what does the pending field mean in this case? Is it necessary?
1. When the sure has a contact, we're showing the contact array of each contact, wouldn't that generate nesting and problems as it can be a huge response? Unless we're going to use it, I'd consider removing that.
1. This is a doubt. What is the criteria in case a user has more than 1 contact, is user A having the worst of the statuses from its contacts unless its own status is worse than all of them? If so, can we sort the statuses from worse (positive) to best (negative) in order to generate the test cases? If this already exists, please point me in the right direction.
1. We're also assuming the final_status as healthy for a user that hasn't taken the survey yet. We should just confirm if this is ok to assume or we should create a new status 'undetermined'

```
 "result": {
        "name": "test_quarentime_user_1_1586502524350 New User 1",
        "initials": "t_quarentime_user_1_1586502524350 NU1",
        "final_status": "healthy",
        "contacts": [],
        "color_hex": "#61C1F7",
        "pending": false
    },
```

@edmarsj @ale90bsas @vlatkozmejkoski

**Comment by edmarsj** [comment]
@jpbottinelli 
1. `Initialls` is a bug, I'll try to get out asap.
2. `Pending` means that the contact hasn't accepted the invitation request, therefore it will be shown as a gray circle on the UI.
3. At this moment we only show one level in the contact trace, so we won't be displaying the contacts of my contacts, but I remember having a conversation where we discussed the necessity of being able to show n.. levels, for now, that field will remain empty. 
4. It will get the worst from it is contact circle. Basically, there are two statuses: Status (my survey result) and FinalStatus (this is my status transformed due to changes in my contact circle, this one is what will be shown to other users that have me as a contact). When a new user is introduced to the circle, or a user status change due to any circumstance, all of his contacts will be "notified" and the system will calculate the FinalStatus by comparing its status with the new contact. This eventually will bubble to other users, but will stop when finding conditions where the status doesn't change. I'll try to draw a diagram for you guys about this process. 
5. This was already fixed. It should be returning a status "pending"

**Comment by jpbottinelli** [comment]
> @jpbottinelli
> 
> 1. `Initialls` is a bug, I'll try to get out asap.
Thanks
> 2. `Pending` means that the contact hasn't accepted the invitation request, therefore it will be shown as a gray circle on the UI.
But this is outside the contact array, which contact does it mean then? I was expecting that this would be inside the 'contact': [{'name': 'A', 'pending': true}, {'name': 'B', pending:false}] for each of them, otherwise, how does it get calculated? same with 'is_direct_contact', I'm not expecting to see it at a main user level, but at a contact level.
> 3. At this moment we only show one level in the contact trace, so we won't be displaying the contacts of my contacts, but I remember having a conversation where we discussed the necessity of being able to show n.. levels, for now, that field will remain empty.
Sounds good
> 4. It will get the worst from it is contact circle. Basically, there are two statuses: Status (my survey result) and FinalStatus (this is my status transformed due to changes in my contact circle, this one is what will be shown to other users that have me as a contact). When a new user is introduced to the circle, or a user status change due to any circumstance, all of his contacts will be "notified" and the system will calculate the FinalStatus by comparing its status with the new contact. This eventually will bubble to other users, but will stop when finding conditions where the status doesn't change. I'll try to draw a diagram for you guys about this process.
Awesome. Pitu already contacted me that they'll be doing the sorting and user scenarios. In the meantime I'll start building some basic test cases.
> 5. This was already fixed. It should be returning a status "pending"
This one is still showing healthy.

Thanks

**Comment by edmarsj** [comment]
- Fixed the initials issue. 
- You were right, I had fixed the initial status in the API, but I didn't fix that on firebase (there's a function trigger that populates these fields upon user creation). I deployed a fix there now.

**Comment by edmarsj** [comment]
Ps. This fix will only reflect new users, please, consider the previously failed cases as bad data.

**Comment by jpbottinelli** [comment]
Tests passed.
Closing ticket so bugs are not addressed, we should keep coming back to this to discuss the other topics
